[project]
authors = ["Samuel Ibarra <Samuel.E.Ibarra@dell.com>"]
channels = ["https://repo.prefix.dev/max-nightly", "https://repo.prefix.dev/conda-forge"]
name = "mnist_mojo"
platforms = ["linux-64", "osx-arm64"]  # Exclude because Mac GPU is not supported
version = "0.1.0"

[tasks]
train = "mojo src/train.mojo"

[dependencies]
mojo = "<1.0.0"
